version: 2.1
executors:
  docker-publisher:
    environment:
      REPO_NAME: teknofile
      IMAGE_NAME: tkfbase
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t ${REPO_NAME}/${IMAGE_NAME}:latest .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar ${IMAGE_NAME}
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load Docker Image From Workspace
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker To Docker Hub
          command: |
            echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker push ${REPO_NAME}/${IMAGE_NAME}:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
