---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: echo "HHeeellloooo"
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: echo "Wooooorld"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
